on: [push, pull_request]

name: build

jobs:
  check:
    name: cosmetics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install compiler
        uses: actions-rs/toolchain@v1
        with:
            profile: "minimal"
            target: "thumbv7m-none-eabi"
            default: true
            components: rustfmt, clippy, llvm-tools-preview

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --release --features use_semihosting
      - name: Run cargo build with semihosting
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features use_semihosting

  build:
    name: build DFU
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install compiler
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2020-03-19
            target: "thumbv7m-none-eabi"
            default: true
            components: llvm-tools-preview

      - name: Install cargo-bloat
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-bloat
          version: latest
          use-tool-cache: true
      - name: Install cargo-binutils
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
          use-tool-cache: true

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target thumbv7m-none-eabi
      - name: Run cargo bloat
        uses: actions-rs/cargo@v1
        with:
          command: bloat
          args: -n 50 --target thumbv7m-none-eabi

      - name: Run cargo objcopy
        uses: actions-rs/cargo@v1
        with:
          command: objcopy
          args: --target thumbv7m-none-eabi --release --bin anne-key -- -O binary anne-key.bin
      # TODO dfu-convert
